language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-storymap' ]; then cd .. && eval "mv $currentfolder generator-storymap" && cd generator-storymap; fi

